name: Create Heroku app on PR open
on:
  pull_request:
    types: [opened]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo ::set-env name=PR_BRANCH_NAME::${BRANCH_NAME}
      - run: echo "app name would be ghostprev-${PR_BRANCH_NAME}"
      - name: test whoami
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku whoami
      - name: create application
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku create ghostprev-${PR_BRANCH_NAME}
