name: Create Heroku app on PR open
on:
  pull_request:
    types: [opened]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: themenamehere
      - uses: actions/checkout@v2
        with:
          repository: SNathJr/ghost-on-heroku
          path: ghost-on-heroku
          fetch-depth: 0 # FIXME https://devcenter.heroku.com/changelog-items/775
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo ::set-env name=PR_BRANCH_NAME::${BRANCH_NAME}
      - run: echo "app name would be ghostprev-${PR_BRANCH_NAME}"
      - name: test whoami
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku whoami
      - name: create application
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku create ghostprev-${PR_BRANCH_NAME} --ssh-git
      - name: mv theme
        run: mv themenamehere ghost-on-heroku/content/themes
      - name: hack .gitignore
        working-directory: ghost-on-heroku
        run: sed -i 's/content\/themes\/\*//' .gitignore
      - name: install Heroku SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HEROKU_SSH_KEY }}
          known_hosts: ${{ secrets.HEROKU_KNOWN_HOSTS }}
      - name: add heroku remote
        working-directory: ghost-on-heroku
        run: git remote add heroku git@heroku.com:ghostprev-${PR_BRANCH_NAME}.git
      - name: push to heroku
        working-directory: ghost-on-heroku
        run: git push heroku master -v -v -v
