name: Destroy Heroku app on PR open
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo ::set-env name=PR_BRANCH_NAME::${BRANCH_NAME}
      - run: echo "app name to destroy would be ghostprev-${PR_BRANCH_NAME}"
